"""esquema inicial

Revision ID: fbba2117b507
Revises: 
Create Date: 2026-06-14 21:18:49.587235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbba2117b507'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ESTUDIANTE', 'DOCENTE', 'BIBLIOTECARIO', 'ADMINISTRADOR', name='rol_usuario', create_constraint=True), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'SANCIONADO', 'INACTIVO', name='estado_usuario', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_dni'), 'usuarios', ['dni'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('libros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=False),
    sa.Column('editorial', sa.String(length=150), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libros_isbn'), 'libros', ['isbn'], unique=True)
    op.create_index(op.f('ix_libros_titulo'), 'libros', ['titulo'], unique=False)
    op.create_table('ejemplares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'PRESTADO', 'MANTENIMIENTO', 'PERDIDO', name='estado_ejemplar', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejemplares_libro_id'), 'ejemplares', ['libro_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADA', 'CANCELADA', 'EXPIRADA', name='estado_reserva', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_libro_id'), 'reservas', ['libro_id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion_real', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'DEVUELTO', 'VENCIDO', name='estado_prestamo', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestamos_ejemplar_id'), 'prestamos', ['ejemplar_id'], unique=False)
    op.create_index(op.f('ix_prestamos_usuario_id'), 'prestamos', ['usuario_id'], unique=False)
    op.create_table('sanciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MORA', 'DANIO', 'PERDIDA', name='tipo_sancion', create_constraint=True), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestamo_id')
    )
    op.create_index(op.f('ix_sanciones_usuario_id'), 'sanciones', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sanciones_usuario_id'), table_name='sanciones')
    op.drop_table('sanciones')
    op.drop_index(op.f('ix_prestamos_usuario_id'), table_name='prestamos')
    op.drop_index(op.f('ix_prestamos_ejemplar_id'), table_name='prestamos')
    op.drop_table('prestamos')
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_libro_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_ejemplares_libro_id'), table_name='ejemplares')
    op.drop_table('ejemplares')
    op.drop_index(op.f('ix_libros_titulo'), table_name='libros')
    op.drop_index(op.f('ix_libros_isbn'), table_name='libros')
    op.drop_table('libros')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_dni'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
